_base_: ${base_config_path}/train_base.yaml

seed: 2026

sr: 44100
n_fft: 2048
hop_length: 512

n_src: 4
n_chan: 2
emb_dim: 96

trainer:
  max_epochs: 900
  check_val_every_n_epoch: 5
  gradient_clip_val: 5.0
  sync_batchnorm: True
  deterministic: false

  limit_train_batches: 110

  benchmark: True
  use_distributed_sampler: False
  precision: bf16-mixed

  callbacks:
    - _target_: lightning.pytorch.callbacks.ModelCheckpoint
      filename: "{epoch:04d}"
      save_top_k: 5
      monitor: validation/loss
      mode: min
      save_last: True
    - _target_: lightning.pytorch.callbacks.RichProgressBar
      refresh_rate: 5
    - _target_: lightning.pytorch.callbacks.RichModelSummary
      max_depth: 3

datamodule:
  _target_: spectral_feature_compression.common.datamodules.hdf5_wav_datamodule.DataModule
  train_dataset_path: 
    - ./recipes/musdb18hq/hdf5/train_bass_seg8sec_sad.hdf5
    - ./recipes/musdb18hq/hdf5/train_drums_seg8sec_sad.hdf5
    - ./recipes/musdb18hq/hdf5/train_vocals_seg8sec_sad.hdf5
    - ./recipes/musdb18hq/hdf5/train_other_seg8sec_sad.hdf5
  val_dataset_path: ./recipes/musdb18hq/hdf5/dev_unsegmented.hdf5
  batch_size: 4
  val_batch_size: 1
  sr: ${sr}
  duration: 6
  val_duration: null
  num_workers: 4
  return_ref: true
  use_scatter_dataset: false
  use_dm_dataset: true
  p_source_dropout: 0.1
  val_drop_last: false

task:
  _target_: spectral_feature_compression.core.tasks.sup_task.SupTask
  n_fft: ${n_fft}
  hop_length: ${hop_length}
  css_validation: true

  ema_weight: 0.999
  ema_update_freq: 1

  model:
    _target_: spectral_feature_compression.core.model.model_wrapper.ModelWrapper
    n_fft: ${n_fft}
    hop_length: ${hop_length}
    fs: ${sr}
    scaling: true

    css_segment_size: 12
    css_shift_size: 6

    model:
      _target_: spectral_feature_compression.core.model.bslocoformer.BSLocoformer
      n_src: ${n_src}
      n_chan: ${n_chan}  # &n_chan 2

      n_layers: 4
      # general setup
      emb_dim: ${emb_dim}
      norm_type: rmsgroupnorm
      num_groups: 4  # used only in RMSGroupNorm
      tf_order: ft
      # self-attention related
      n_heads: 4
      flash_attention: true  # available when using mixed precision
      attention_dim: 96
      # ffn related
      ffn_type: 
        - swiglu_conv1d
        - swiglu_conv1d
      ffn_hidden_dim: 
        - 128
        - 128
      conv1d_kernel: 8
      conv1d_shift: 1
      dropout: 0.1
      # others
      eps: 1.0e-5

      encoder:
        _target_: spectral_feature_compression.core.model.crossattn_enc_dec.CrossAttnEncoder
        # general SFC config
        d_inner: &d_inner 64
        d_model: ${emb_dim}
        n_chan: ${n_chan}
        sample_rate: ${sr}
        n_fft: ${n_fft}
        n_bands: &n_bands 64
        band_config: &band_config musical
        query_type: &query_type learnable
        # cross-attention related
        n_heads: &n_heads 4
        slope: &slope  [1, 1, 1, 1]
        learnable_slope: &learnable_slope false
        learnable_pos_bias: &learnable_pos_bias true
        mask_outside_bands: &mask_outside_bands false
        

      decoder:
        _target_: spectral_feature_compression.core.model.crossattn_enc_dec.CrossAttnDecoder
        # general SFC config
        d_inner: *d_inner
        d_model: ${emb_dim}
        n_src: ${n_src}
        n_chan: ${n_chan}
        sample_rate: ${sr}
        n_fft: ${n_fft}
        n_bands: *n_bands
        band_config: *band_config
        query_type: *query_type
        # cross-attention related
        n_heads: *n_heads
        slope: *slope
        learnable_slope: *learnable_slope
        learnable_pos_bias: *learnable_pos_bias
        mask_outside_bands: *mask_outside_bands
 
  loss:
    _target_: spectral_feature_compression.core.loss.snr.ThresSNRLossWithInactiveSource
    solve_perm: false
    n_src: ${n_src}
    zeroref_weight: 0.1
    only_denominator: false


  optimizer_config:
    _target_: aiaccel.torch.lightning.OptimizerConfig
    optimizer_generator:
      _partial_: True
      _target_: torch.optim.AdamW
      lr: 1.e-3
      weight_decay: 1.e-2
      betas:
        - 0.9
        - 0.999
    scheduler_generator:
      _partial_: True
      _target_: spectral_feature_compression.common.lr_schedulers.warmup.WarmUpStepLR
      warmup_steps: 5000
      decay_start_step: 60500  # 110 steps x 550 epochs
      decay_stop_step: 99000  # 110 steps x 990 epochs
      step_size: 220  # 2 epochs
      decay: 0.98
    scheduler_interval: step